name: munin
description: Flutter + BangumiN == Munin (a new Bangumi App)

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.6.0+18

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ^1.22.0

dependencies:
  flutter:
    sdk: flutter
  badges: ^1.1.3
  bbob_dart: ^0.1.0
  built_collection: ^4.3.2
  built_value: ^7.1.0
  #  please pay extra attention while upgrading cached_network_image as there is no test for this dep
  cached_network_image: 2.3.2+1
  cookie_jar: ^1.0.1
  device_info: ^0.4.2+8
  expandable: ^3.0.0+1
  dio: ^3.0.10
  dio_cookie_manager: ^1.0.0
  firebase_analytics: ^6.0.1
  firebase_core: ^0.5.0
  firebase_crashlytics: ^0.2.1
  fluro: ^1.6.3
  flutter_redux: ^0.6.0
  flutter_secure_storage: ^3.3.4
  flutter_svg: ^0.19.0
  flutter_widget_from_html: ^0.5.0+7
  get_it: ^5.0.1
  html: ^0.14.0+2
  http: ^0.12.2
  intl: ^0.16.1
  image_gallery_saver: ^1.5.0
  material_design_icons_flutter: ^4.0.5655
  markdown: ^2.1.8
  #  Wait for https://github.com/flutter/packages/pull/22 to be resolved to switch back to offcial.
  palette_generator: ^0.2.3
  permission_handler: ^5.0.1+1
  screen: ^0.0.5
  transparent_image: ^1.0.0
  timeago: ^2.0.27
  oauth2: ^1.6.1
  package_info: ^0.4.3
  pub_semver: ^1.4.2
  redux_epics: ^0.14.0
  redux_logging: ^0.4.0
  rxdart: ^0.24.1
  share: ^0.6.5+2
  shared_preferences: ^0.5.12
  tuple: ^1.0.2
  quiver: ^2.0.2
  url_launcher: ^5.7.2
  upgrader: ^2.6.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.7.2
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
  built_value_generator: ^7.0.0
  dio_retry: ^0.1.8-beta
  logging: ^0.11.3+2
  test: ^1.6.1
  mockito: ^4.1.0

#ã€€Run `flutter pub run flutter_launcher_icons:main` to generate new icons.
flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/logo/munin_logo_padding_rounded_2048x2048.png"
  image_path_ios: "assets/logo/munin_logo_full_2048x2048.png"
  adaptive_icon_background: "#FFF09199"
  adaptive_icon_foreground: "assets/logo/munin_logo_padding_rounded_2048x2048.png"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo/munin_logo_rounded.svg
    - assets/stickers/bangumi/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  fonts:
    - family: MuninIcons
      fonts:
        - asset: fonts/icons/munin/MuninIcons.ttf
